/*[
	AccessNode, 
	Actual, 
	Argument, 
	ArrayType, 
	BooleanType, 
	Caller, 
	Characters, 
	Collector, 
	CompileState, 
	Console, 
	ConstructionCaller, 
	ConstructorHeader, 
	Definition, 
	DivideState, 
	EmptyHead, 
	Err, 
	Files, 
	FlatMapHead, 
	FunctionHeader, 
	FunctionSegment, 
	FunctionType, 
	Head, 
	HeadedQuery, 
	IOError, 
	ImmutableCompileState, 
	Import, 
	Joiner, 
	List, 
	ListCollector, 
	Lists, 
	MapHead, 
	Namespace, 
	None, 
	Ok, 
	Option, 
	Parameter, 
	Path, 
	Placeholder, 
	PrimitiveType, 
	Queries, 
	Query, 
	RangeHead, 
	Result, 
	SingleHead, 
	SliceType, 
	Some, 
	Strings, 
	TemplateType, 
	Tuple2, 
	Tuple2Impl, 
	Type, 
	VariadicType, 
	Whitespace, 
	ZipHead
]*/
#ifndef magma_app_compile_value_ConstructorHeader
#define magma_app_compile_value_ConstructorHeader
import { ConstructorHeader } from "magma/app/compile/value/ConstructorHeader";
import { FunctionHeader } from "magma/app/compile/define/FunctionHeader";
import { Platform } from "magma/app/io/Platform";
import { Definition } from "magma/app/compile/define/Definition";
import { List } from "magma/api/collect/list/List";
import { Joiner } from "magma/api/collect/Joiner";
#endif
