@startuml
skinparam linetype ortho
class Main
Main --> State
Main --> IOException
Main --> Files
Main --> Path
Main --> Paths
Main --> List
Main --> Set
Main --> Collectors
Main --> Stream
class State
State --> ArrayList
State --> List
@enduml
