@startuml
skinparam linetype ortho
class Main
Main --> IOException
Main --> Files
Main --> Path
Main --> Paths
Main --> ArrayList
Main --> List
Main --> Set
Main --> Collectors
Main --> Stream
@enduml
