@startuml
class Lists {
}
class Files {
}
interface Actual {
}
interface Namespace {
}
interface Collector<T, C> {
}
class EmptyHead<T> {
}
EmptyHead <|.. Head
class FlatMapHead<T, R> {
}
FlatMapHead <|.. Head
interface Head<T> {
}
class HeadedIter<T> {
}
HeadedIter <|.. Iter
class MapHead<T, R> {
}
MapHead <|.. Head
class RangeHead {
}
RangeHead <|.. Head
class SingleHead<T> {
}
SingleHead <|.. Head
interface Iter<T> {
}
class Iters {
}
class Joiner {
}
Joiner <|.. Collector
interface List<T> {
}
class ListCollector<T> {
}
ListCollector <|.. Collector
class Console {
}
interface IOError {
}
interface Path {
}
class None<T> {
}
None <|.. Option
interface Option<T> {
}
class Some<T> {
}
Some <|.. Option
class Err<T, X> {
}
Err <|.. Result
class Ok<T, X> {
}
Ok <|.. Result
interface Result<T, X> {
}
class Characters {
}
class Strings {
}
interface Tuple2<A, B> {
}
class Tuple2Impl<A, B> {
}
Tuple2Impl <|.. Tuple2
interface CompileState {
}
class ConstructionCaller {
}
ConstructionCaller <|.. Caller
class ConstructorHeader {
}
ConstructorHeader <|.. MethodHeader
class Definition {
}
interface MethodHeader {
}
interface Parameter {
}
interface DivideState {
}
class ImmutableCompileState {
}
ImmutableCompileState <|.. CompileState
class ImmutableDivideState {
}
ImmutableDivideState <|.. DivideState
class Import {
}
class Placeholder {
}
class Symbol {
}
class Whitespace {
}
Whitespace <|.. Parameter
class FunctionType {
}
FunctionType <|.. Type
class PrimitiveType {
}
PrimitiveType <|.. Type
class TemplateType {
}
TemplateType <|.. Type
interface Type {
}
class VariadicType {
}
VariadicType <|.. Type
class AccessValue {
}
AccessValue <|.. Value
interface Argument {
}
interface Caller {
}
class Invokable {
}
Invokable <|.. Value
class Lambda {
}
Lambda <|.. Value
class Not {
}
Not <|.. Value
class Operation {
}
Operation <|.. Value
class StringValue {
}
StringValue <|.. Value
interface Value {
}
Value <|-- Argument
Value <|-- Caller
class Source {
}
class Main {
}
class Platform {
}
@enduml