import { List } from "../../../magmac/api/collect/list/List";
import { Lists } from "../../../magmac/api/collect/list/Lists";
import { Joiner } from "../../../magmac/api/iter/collect/Joiner";
import { ListCollector } from "../../../magmac/api/iter/collect/ListCollector";
import { CompileResult } from "../../../magmac/app/compile/error/CompileResult";
import { CompileResultCollector } from "../../../magmac/app/compile/error/CompileResultCollector";
import { CompileResults } from "../../../magmac/app/compile/error/CompileResults";
import { Location } from "../../../magmac/app/io/Location";
import { UnitSetCollector } from "../../../magmac/app/io/sources/UnitSetCollector";
import { ArrayType } from "../../../magmac/app/lang/node/ArrayType";
import { Constructor } from "../../../magmac/app/lang/node/Constructor";
import { Definition } from "../../../magmac/app/lang/node/Definition";
import { EnumValues } from "../../../magmac/app/lang/node/EnumValues";
import { JavaArrayType } from "../../../magmac/app/lang/node/JavaArrayType";
import { JavaBase } from "../../../magmac/app/lang/node/JavaBase";
import { JavaDefinition } from "../../../magmac/app/lang/node/JavaDefinition";
import { JavaMethod } from "../../../magmac/app/lang/node/JavaMethod";
import { JavaMethodHeader } from "../../../magmac/app/lang/node/JavaMethodHeader";
import { JavaNamespacedNode } from "../../../magmac/app/lang/node/JavaNamespacedNode";
import { JavaParameter } from "../../../magmac/app/lang/node/JavaParameter";
import { JavaRootSegment } from "../../../magmac/app/lang/node/JavaRootSegment";
import { JavaStructureMember } from "../../../magmac/app/lang/node/JavaStructureMember";
import { JavaStructureNode } from "../../../magmac/app/lang/node/JavaStructureNode";
import { JavaTemplateType } from "../../../magmac/app/lang/node/JavaTemplateType";
import { JavaType } from "../../../magmac/app/lang/node/JavaType";
import { ParameterizedMethodHeader } from "../../../magmac/app/lang/node/ParameterizedMethodHeader";
import { QualifiedType } from "../../../magmac/app/lang/node/QualifiedType";
import { Root } from "../../../magmac/app/lang/node/Root";
import { Segment } from "../../../magmac/app/lang/node/Segment";
import { StructureStatement } from "../../../magmac/app/lang/node/StructureStatement";
import { StructureValue } from "../../../magmac/app/lang/node/StructureValue";
import { Symbol } from "../../../magmac/app/lang/node/Symbol";
import { TypeArguments } from "../../../magmac/app/lang/node/TypeArguments";
import { TypeScriptDefinition } from "../../../magmac/app/lang/node/TypeScriptDefinition";
import { TypeScriptImport } from "../../../magmac/app/lang/node/TypeScriptImport";
import { TypeScriptMethodHeader } from "../../../magmac/app/lang/node/TypeScriptMethodHeader";
import { TypeScriptParameter } from "../../../magmac/app/lang/node/TypeScriptParameter";
import { TypeScriptRootSegment } from "../../../magmac/app/lang/node/TypeScriptRootSegment";
import { TypeScriptTemplateType } from "../../../magmac/app/lang/node/TypeScriptTemplateType";
import { TypeScriptType } from "../../../magmac/app/lang/node/TypeScriptType";
import { TypescriptArrayType } from "../../../magmac/app/lang/node/TypescriptArrayType";
import { TypescriptMethod } from "../../../magmac/app/lang/node/TypescriptMethod";
import { TypescriptRoot } from "../../../magmac/app/lang/node/TypescriptRoot";
import { TypescriptStructureMember } from "../../../magmac/app/lang/node/TypescriptStructureMember";
import { TypescriptStructureNode } from "../../../magmac/app/lang/node/TypescriptStructureNode";
import { TypescriptStructureType } from "../../../magmac/app/lang/node/TypescriptStructureType";
import { VariadicType } from "../../../magmac/app/lang/node/VariadicType";
import { Whitespace } from "../../../magmac/app/lang/node/Whitespace";
import { Parser } from "../../../magmac/app/stage/parse/Parser";
import { SimpleUnit } from "../../../magmac/app/stage/unit/SimpleUnit";
import { Unit } from "../../../magmac/app/stage/unit/Unit";
import { UnitSet } from "../../../magmac/app/stage/unit/UnitSet";
export class JavaTypescriptParser {
	parseUnit(unit : Unit<Root<JavaRootSegment>>) : CompileResult<Unit<TypescriptRoot>>;
	parseRoot(location : Location, root : Root<JavaRootSegment>) : CompileResult<Unit<TypescriptRoot>>;
	parseRootSegment(location : Location, rootSegment : JavaRootSegment) : TypeScriptRootSegment;
	parseJavaStructure(structureNode : JavaStructureNode) : TypeScriptRootSegment;
	parseClass(structureNode : JavaStructureNode) : TypescriptStructureNode;
	parseTypeList(list : List<JavaType>) : List<TypeScriptType>;
	parseStructureMember(structureNode : JavaStructureMember) : TypescriptStructureMember;
	parseMethod(methodNode : JavaMethod) : TypescriptStructureMember;
	parseParameter(parameter : JavaParameter) : TypeScriptParameter;
	parseMethodHeader(header : JavaMethodHeader) : TypeScriptMethodHeader;
	parseDefinition(javaDefinition : JavaDefinition) : TypeScriptDefinition;
	parseArrayType(type : JavaArrayType) : TypeScriptType;
	parseType(variadicType : JavaType) : TypeScriptType;
	parseTemplateType(type : JavaTemplateType) : TypeScriptTemplateType;
	parseBaseType(base : JavaBase) : Symbol;
	parseNamespaced(location : Location, namespaced : JavaNamespacedNode) : TypeScriptRootSegment;
	parseImport(location : Location, segments : List<Segment>) : TypeScriptImport;
	apply(initial : UnitSet<Root<JavaRootSegment>>) : CompileResult<UnitSet<TypescriptRoot>>;
}
