#include <temp.h>
#include <temp.h>
#include <temp.h>
#include <temp.h>
#include <temp.h>
#include <temp.h>
#include <temp.h>
#include <temp.h>
#include <temp.h>
#include <temp.h>
#include <temp.h>
#include <temp.h>
#include <temp.h>
#include <temp.h>
#include <temp.h>
#include <temp.h>
#include <temp.h>
#include <temp.h>
#include <temp.h>
/* List_String*//* ArrayList_String*//* Optional_String*//* Optional_/* ? extends String*/*//* Optional_/* ? extends DivideState*/*//* Optional_DivideState*/typedef struct {
	String value;
} String_;
/* Tuple_String_List_String*//* Tuple_char_List__char*//* Tuple_char_DivideState*//* Tuple_String_List__String*/typedef struct {
	String_ beforeType;
	String_ type;
	String_ name;
	int (*equals)();
	int (*hashCode)();
	String (*toString)();
} Node;
/* List__char*//* List__String*/typedef struct {
	DivideState (*popAndAppend)();
	DivideState (*advance)();
	DivideState (*append)();
	List__String (*segments)();
	int (*isLevel)();
	DivideState (*enter)();
	DivideState (*exit)();
	int (*isShallow)();
	int (*hasNext)();
	Tuple_char_DivideState (*pop)();
} DivideState;
typedef struct {
	List__char queue;
	List__String segments;
	StringBuilder buffer;
	int depth;
	DivideState (*advance)();
	DivideState (*append)();
	int (*isLevel)();
	DivideState (*enter)();
	DivideState (*exit)();
	int (*isShallow)();
	int (*hasNext)();
	Tuple_char_DivideState (*pop)();
	DivideState (*popAndAppend)();
	List__String (*segments)();
} MutableDivideState;
typedef struct {
} Main;
