Iters --> Main
Application --> Main
CompileApplication --> Main
Config --> Main
Error --> Main
Compiler --> Main
StagedCompiler --> Main
Rule --> Main
PathSources --> Main
Sources --> Main
PathTargets --> Main
Targets --> Main
AfterPasser --> Main
JavaToPlantUML --> Main
MergeDiagram --> Main
PlantUMLRoots --> Main
TargetPlatform --> Main
AfterAll --> Main
EmptyAfterAll --> Main
Generator --> Main
RuleGenerator --> Main
Lexer --> Main
Parser --> Main
TreeParser --> Main
Path --> Main
Paths --> Main
Optional --> Main
class Main
