clang .\magma\app\compile\ImmutableState.c^
	 .\magma\api\collect\Head.c^
	 .\jv\api\collect\HeadedStream.c^
	 .\magma\app\compile\CompileError.c^
	 .\magma\api\result\Result.c^
	 .\jv\api\collect\JavaLists.c^
	 .\jv\api\result\ThrowableRunnable.c^
	 .\magma\api\option\None.c^
	 .\jv\api\JavaOptions.c^
	 .\jv\api\result\JavaResults.c^
	 .\jv\api\io\JavaList.c^
	 .\magma\api\result\Err.c^
	 .\jv\api\error\ThrowableError.c^
	 .\magma\app\ApplicationError.c^
	 .\magma\api\option\Some.c^
	 .\magma\api\collect\Stream.c^
	 .\magma\api\result\Tuple.c^
	 .\magma\api\collect\List_.c^
	 .\magma\api\io\IOError.c^
	 .\magma\api\error\Error.c^
	 .\jv\api\result\ThrowableSupplier.c^
	 .\jv\api\io\JavaFiles.c^
	 .\magma\Compiler.c^
	 .\magma\Main.c^
	 .\magma\app\compile\State.c^
	 .\magma\api\option\Option.c^
	 .\jv\app\compile\PathSource.c^
	 .\magma\Application.c^
	 .\magma\api\collect\RangeHead.c^
	 .\magma\app\compile\Source.c^
	 .\jv\api\io\JavaIOError.c^
	 .\magma\api\result\Ok.c^
	 -o main.exe