@startuml
skinparam linetype ortho
interface Filter

class ListCollector
Collector <|-- ListCollector

class RangeHead
Head <|-- RangeHead

interface Source

class TypeScriptTargetPlatform
TargetPlatform <|-- TypeScriptTargetPlatform

interface Roots

interface Targets

class FlatMapHead
Head <|-- FlatMapHead

interface TargetPlatform

class CommonLang

class Joiner
Collector <|-- Joiner

class FlattenJava
Passer <|-- FlattenJava

class JavaLang

class StringRule
Rule <|-- StringRule

class ThrowableError
Error <|-- ThrowableError

class Tuple2

class ApplicationError
Error <|-- ApplicationError

class StagedCompiler
Compiler <|-- StagedCompiler

interface Head

class StatementFolder
Folder <|-- StatementFolder

class CompileErrors

interface Generator
Stage <|-- Generator

interface Compiler

class NodeContext
Context <|-- NodeContext

class TypescriptRoots

class ImmutableCompileError
CompileError <|-- ImmutableCompileError

class EmptyHead
Head <|-- EmptyHead

interface NodeList

interface Stage

class MapCollector
Collector <|-- MapCollector

interface Folder

class PathSources
Sources <|-- PathSources

class ResultCollector
Collector <|-- ResultCollector

interface DivideState

class PlantUMLTargetPlatform
TargetPlatform <|-- PlantUMLTargetPlatform

class MapRoots
Roots <|-- MapRoots

interface CompileError
Error <|-- CompileError

class SymbolFilter
Filter <|-- SymbolFilter

class RuleGenerator
Generator <|-- RuleGenerator

interface Passer

class NumberFilter
Filter <|-- NumberFilter

class PrefixRule
Rule <|-- PrefixRule

class RuleLexer
Lexer <|-- RuleLexer

class EmptyAfterAll
AfterAll <|-- EmptyAfterAll

class CompileApplication
Application <|-- CompileApplication

class ExactRule
Rule <|-- ExactRule

class PathSource
Source <|-- PathSource

interface Collector

class StringContext
Context <|-- StringContext

class TypeRule
Rule <|-- TypeRule

class InlineNodeList
NodeList <|-- InlineNodeList

class FirstLocator
Locator <|-- FirstLocator

class OrState

interface Node

class OrRule
Rule <|-- OrRule

interface ParseState

interface Iter

class NodeRule
Rule <|-- NodeRule

class Iters

interface Rule

interface Error

class ApplicationBuilder

class DelimitedFolder
Folder <|-- DelimitedFolder

class PathTargets
Targets <|-- PathTargets

class Location

class SingleHead
Head <|-- SingleHead

interface Context

class StripRule
Rule <|-- StripRule

class MergeDiagram
AfterAll <|-- MergeDiagram

class Ok
Result <|-- Ok

interface Sources

interface Parser
Stage <|-- Parser

interface Application

class ImmutableParseState
ParseState <|-- ImmutableParseState

interface Lexer
Stage <|-- Lexer

class DivideRule
Rule <|-- DivideRule

class TreeParser
Parser <|-- TreeParser

class Err
Result <|-- Err

class CompileResult

class LocatingRule
Rule <|-- LocatingRule

class SuffixRule
Rule <|-- SuffixRule

class AfterPasser
Passer <|-- AfterPasser

class TypeScriptPasser
Passer <|-- TypeScriptPasser

interface Result

interface AfterAll

class PlantUMLLang

class Main

class SafeFiles

class LastLocator
Locator <|-- LastLocator

class HeadedIter
Iter <|-- HeadedIter

class MutableDivideState
DivideState <|-- MutableDivideState

interface Locator

class MapNode
Node <|-- MapNode

class ContextRule
Rule <|-- ContextRule

class FilterRule
Rule <|-- FilterRule

Iters --> Tuple2
Iters --> EmptyHead
Iters --> HeadedIter
Iters --> RangeHead
Iters --> SingleHead
Iters --> ArrayList
Iters --> List
Iters --> Map
Iters --> Optional
MergeDiagram --> Tuple2
MergeDiagram --> ListCollector
MergeDiagram --> Iters
MergeDiagram --> InlineNodeList
MergeDiagram --> MapNode
MergeDiagram --> NodeList
MergeDiagram --> ArrayList
MergeDiagram --> Collection
MergeDiagram --> Collections
MergeDiagram --> HashMap
MergeDiagram --> List
Roots --> Tuple2
Roots --> Iter
Roots --> Node
Roots --> Location
Node --> Tuple2
Node --> Iter
Node --> Optional
ParseState --> Location
FilterRule --> CompileErrors
FlatMapHead --> Iter
FlatMapHead --> Function
Passer --> Tuple2
Passer --> Node
Passer --> ParseState
Passer --> Optional
Result --> Tuple2
Result --> Function
Result --> Supplier
ApplicationBuilder --> Error
ApplicationBuilder --> Compiler
ApplicationBuilder --> StagedCompiler
ApplicationBuilder --> TargetPlatform
ApplicationBuilder --> Sources
ApplicationBuilder --> PathTargets
ApplicationBuilder --> Targets
ApplicationBuilder --> FlattenJava
ApplicationBuilder --> JavaLang
ApplicationBuilder --> AfterAll
ApplicationBuilder --> Passer
ApplicationBuilder --> Generator
ApplicationBuilder --> RuleGenerator
ApplicationBuilder --> Lexer
ApplicationBuilder --> RuleLexer
ApplicationBuilder --> Parser
ApplicationBuilder --> TreeParser
ApplicationBuilder --> Path
ApplicationBuilder --> Optional
OrState --> Err
OrState --> Ok
OrState --> Result
OrState --> CompileError
OrState --> Context
OrState --> ImmutableCompileError
OrState --> ArrayList
OrState --> List
OrState --> Optional
DivideRule --> Tuple2
DivideRule --> Joiner
DivideRule --> ListCollector
DivideRule --> ResultCollector
DivideRule --> Iter
DivideRule --> Iters
DivideRule --> CompileErrors
DivideRule --> InlineNodeList
DivideRule --> MapNode
DivideRule --> NodeList
DivideRule --> DivideState
DivideRule --> MutableDivideState
DivideRule --> Folder
DivideRule --> StatementFolder
DivideRule --> Optional
Locator --> Optional
ListCollector --> ArrayList
ListCollector --> List
Stage --> Result
Stage --> CompileError
Iter --> Collector
Iter --> Result
Iter --> Optional
Iter --> BiFunction
Iter --> Function
Iter --> Predicate
ResultCollector --> Ok
ResultCollector --> Result
AfterPasser --> ListCollector
AfterPasser --> Iter
AfterPasser --> Iters
AfterPasser --> InlineNodeList
AfterPasser --> MapNode
AfterPasser --> NodeList
PrefixRule --> CompileErrors
Compiler --> Location
Compiler --> Map
Head --> Optional
OrRule --> Context
OrRule --> NodeContext
OrRule --> StringContext
OrRule --> List
OrRule --> Function
NodeContext --> Node
NodeList --> Iter
PathSource --> SafeFiles
PathSource --> Path
PathSource --> ArrayList
PathSource --> Collections
PathSource --> List
CompileErrors --> Err
CompileErrors --> Result
CompileErrors --> NodeContext
CompileErrors --> StringContext
CompileErrors --> Node
CompileErrors --> ImmutableCompileError
DivideState --> Tuple2
DivideState --> Optional
DivideState --> Stream
PathTargets --> Iters
PathTargets --> SafeFiles
PathTargets --> Files
PathTargets --> Path
Sources --> Result
Sources --> Location
Sources --> IOException
Sources --> Map
Parser --> Roots
HeadedIter --> Ok
Lexer --> Location
Lexer --> Roots
Lexer --> Map
TreeParser --> Tuple2
TreeParser --> MapCollector
TreeParser --> Ok
TreeParser --> Result
TreeParser --> CompileError
TreeParser --> InlineNodeList
TreeParser --> Node
TreeParser --> NodeList
TreeParser --> Location
TreeParser --> AfterAll
TreeParser --> MapRoots
TreeParser --> Passer
TreeParser --> Map
MapRoots --> Iters
MapRoots --> Map
InlineNodeList --> Iters
InlineNodeList --> ArrayList
InlineNodeList --> List
TypescriptRoots --> DivideRule
TypescriptRoots --> ExactRule
TypescriptRoots --> LocatingRule
TypescriptRoots --> OrRule
TypescriptRoots --> PrefixRule
TypescriptRoots --> Rule
TypescriptRoots --> StringRule
TypescriptRoots --> SuffixRule
TypescriptRoots --> TypeRule
TypescriptRoots --> List
Rule --> Result
Rule --> CompileError
Rule --> Node
RuleGenerator --> Tuple2
RuleGenerator --> MapCollector
RuleGenerator --> ResultCollector
RuleGenerator --> Result
RuleGenerator --> CompileError
RuleGenerator --> Rule
Application --> Error
Application --> Optional
Generator --> Location
Generator --> Roots
Generator --> Map
StringRule --> Err
StringRule --> Ok
StringRule --> CompileErrors
StringRule --> NodeContext
StringRule --> MapNode
StringRule --> ImmutableCompileError
MapNode --> Joiner
MapNode --> Iters
MapNode --> HashMap
MapNode --> Map
MapNode --> BiFunction
MapNode --> Function
MapNode --> Collectors
MapNode --> Stream
Folder --> DivideState
Source --> Result
Source --> Location
Source --> IOException
PathSources --> Tuple2
PathSources --> MapCollector
PathSources --> ResultCollector
PathSources --> SafeFiles
PathSources --> Files
PathSources --> Path
ThrowableError --> PrintWriter
ThrowableError --> StringWriter
ExactRule --> Ok
ExactRule --> CompileErrors
ExactRule --> MapNode
TargetPlatform --> Rule
TargetPlatform --> AfterAll
TargetPlatform --> Passer
TargetPlatform --> Path
AfterAll --> Node
AfterAll --> Location
AfterAll --> Map
MapCollector --> Tuple2
MapCollector --> HashMap
MapCollector --> Map
TypeScriptTargetPlatform --> TypeScriptPasser
TypeScriptTargetPlatform --> TypescriptRoots
TypeScriptTargetPlatform --> EmptyAfterAll
TypeScriptTargetPlatform --> Paths
Joiner --> Optional
ImmutableCompileError --> Context
ImmutableCompileError --> ArrayList
ImmutableCompileError --> Comparator
ImmutableCompileError --> List
ImmutableCompileError --> Collectors
SafeFiles --> Iter
SafeFiles --> Iters
SafeFiles --> Err
SafeFiles --> Ok
SafeFiles --> Result
SafeFiles --> IOException
SafeFiles --> Files
SafeFiles --> Path
SafeFiles --> Optional
SafeFiles --> Collectors
SafeFiles --> Stream
Targets --> Location
Targets --> IOException
Targets --> Map
Targets --> Optional
StagedCompiler --> Result
StagedCompiler --> CompileError
StagedCompiler --> Generator
StagedCompiler --> Lexer
StagedCompiler --> Parser
MutableDivideState --> ArrayList
MutableDivideState --> List
CompileApplication --> Compiler
CompileApplication --> ApplicationError
CompileApplication --> ThrowableError
CompileApplication --> Location
CompileApplication --> Sources
CompileApplication --> Targets
CompileApplication --> Map
ContextRule --> NodeContext
ContextRule --> StringContext
ContextRule --> ImmutableCompileError
ContextRule --> List
PlantUMLTargetPlatform --> AfterPasser
PlantUMLTargetPlatform --> MergeDiagram
PlantUMLTargetPlatform --> PlantUMLLang
PlantUMLTargetPlatform --> Paths
CommonLang --> ExactRule
CommonLang --> Rule
CommonLang --> StripRule
CommonLang --> TypeRule
LocatingRule --> CompileErrors
LocatingRule --> FirstLocator
LocatingRule --> LastLocator
LocatingRule --> Locator
LocatingRule --> Optional
NodeRule --> Ok
NodeRule --> CompileErrors
NodeRule --> MapNode
SuffixRule --> Err
SuffixRule --> CompileErrors
SuffixRule --> StringContext
SuffixRule --> ImmutableCompileError
JavaLang --> ContextRule
JavaLang --> DivideRule
JavaLang --> LocatingRule
JavaLang --> NodeRule
JavaLang --> OrRule
JavaLang --> PrefixRule
JavaLang --> Rule
JavaLang --> StringRule
JavaLang --> StripRule
JavaLang --> SuffixRule
JavaLang --> FilterRule
JavaLang --> TypeRule
JavaLang --> DelimitedFolder
JavaLang --> List
CompileResult --> Result
CompileResult --> CompileError
PlantUMLLang --> DivideRule
PlantUMLLang --> ExactRule
PlantUMLLang --> LocatingRule
PlantUMLLang --> OrRule
PlantUMLLang --> PrefixRule
PlantUMLLang --> Rule
PlantUMLLang --> StringRule
PlantUMLLang --> SuffixRule
PlantUMLLang --> TypeRule
PlantUMLLang --> StatementFolder
PlantUMLLang --> List
Main --> Iters
Main --> ApplicationBuilder
Main --> Error
Main --> PlantUMLTargetPlatform
Main --> TypeScriptTargetPlatform
Main --> PathSources
Main --> Sources
Main --> Paths
FlattenJava --> ListCollector
FlattenJava --> InlineNodeList
FlattenJava --> NodeList
RuleLexer --> Tuple2
RuleLexer --> Iters
RuleLexer --> MapCollector
RuleLexer --> ResultCollector
RuleLexer --> Result
RuleLexer --> CompileError
RuleLexer --> Node
RuleLexer --> Rule
RuleLexer --> MapRoots
TypeRule --> CompileErrors
TypeRule --> Context
TypeRule --> NodeContext
TypeRule --> StringContext
TypeRule --> ImmutableCompileError
TypeRule --> List
Location --> List
@enduml
