@startuml
skinparam linetype ortho
BlockHeader --> Lists
BlockHeader --> CompileResult
BlockHeader --> Node
BlockHeader --> ExactRule
BlockHeader --> NodeRule
BlockHeader --> OrRule
BlockHeader --> PrefixRule
BlockHeader --> Rule
BlockHeader --> StripRule
BlockHeader --> SuffixRule
BlockHeader --> TypeRule
BlockHeader --> Deserializers
interface BlockHeader
StructureValue --> Option
StructureValue --> List
StructureValue --> MapNode
StructureValue --> Node
StructureValue --> Serializable
class StructureValue
PlantUMLRootSegments --> Lists
PlantUMLRootSegments --> OrRule
PlantUMLRootSegments --> Rule
PlantUMLRootSegments --> SuffixRule
class PlantUMLRootSegments
List --> Option
List --> Tuple2
List --> Iter
List --> BiFunction
interface List
PlantUMLInherits --> MapNode
PlantUMLInherits --> Node
PlantUMLInherits --> LocatingRule
PlantUMLInherits --> StringRule
PlantUMLInherits --> TypeRule
class PlantUMLInherits
PlantUMLRootSegment <|-- PlantUMLInherits
Base --> Serializable
interface Base
Serializable <|-- Base
Root --> List
Root --> MapNode
Root --> Node
Root --> Rule
Root --> TypeRule
Root --> CommonLang
Root --> Serializable
class Root
Serializable <|-- Root
TargetPlatform --> Application
TargetPlatform --> Compiler
TargetPlatform --> Rule
TargetPlatform --> Path
interface TargetPlatform
Joiner --> None
Joiner --> Option
Joiner --> Some
class Joiner
Collector <|-- Joiner
ListCollector --> List
ListCollector --> Lists
class ListCollector
Collector <|-- ListCollector
interface FunctionSegmentValue
JavaStructureNodeDeserializer --> Option
JavaStructureNodeDeserializer --> Tuple2
JavaStructureNodeDeserializer --> List
JavaStructureNodeDeserializer --> CompileResult
JavaStructureNodeDeserializer --> CompoundDestructor
JavaStructureNodeDeserializer --> InitialDestructor
JavaStructureNodeDeserializer --> Node
JavaStructureNodeDeserializer --> Deserializers
class JavaStructureNodeDeserializer
TypedDeserializer <|-- JavaStructureNodeDeserializer
Catch --> Option
Catch --> CompileResult
Catch --> Node
Catch --> Deserializers
class Catch
BlockHeader <|-- Catch
AssignmentNode --> Option
AssignmentNode --> Lists
AssignmentNode --> CompileResult
AssignmentNode --> Node
AssignmentNode --> LocatingRule
AssignmentNode --> NodeRule
AssignmentNode --> OrRule
AssignmentNode --> Rule
AssignmentNode --> TypeRule
AssignmentNode --> Deserializers
class AssignmentNode
FunctionSegmentValue <|-- AssignmentNode
ApplicationError --> Error
class ApplicationError
Error <|-- ApplicationError
PlantUMLStructure --> MapNode
PlantUMLStructure --> Node
PlantUMLStructure --> PrefixRule
PlantUMLStructure --> Rule
PlantUMLStructure --> StringRule
PlantUMLStructure --> TypeRule
class PlantUMLStructure
PlantUMLRootSegment <|-- PlantUMLStructure
FunctionSegment --> Lists
FunctionSegment --> CompileResult
FunctionSegment --> Node
FunctionSegment --> ExactRule
FunctionSegment --> LocatingRule
FunctionSegment --> NodeListRule
FunctionSegment --> NodeRule
FunctionSegment --> OrRule
FunctionSegment --> PrefixRule
FunctionSegment --> Rule
FunctionSegment --> StringRule
FunctionSegment --> StripRule
FunctionSegment --> SuffixRule
FunctionSegment --> TypeRule
FunctionSegment --> StatementFolder
FunctionSegment --> Deserializers
FunctionSegment --> LazyRule
interface FunctionSegment
Access --> Option
Access --> CompileResult
Access --> Node
Access --> LocatingRule
Access --> NodeRule
Access --> Rule
Access --> TypeRule
Access --> LazyRule
Access --> Deserializers
class Access
Value <|-- Access
AfterAll --> Node
AfterAll --> UnitSet
interface AfterAll
CompoundDestructorImpl --> None
CompoundDestructorImpl --> Option
CompoundDestructorImpl --> Some
CompoundDestructorImpl --> Tuple2
CompoundDestructorImpl --> List
CompoundDestructorImpl --> ListCollector
CompoundDestructorImpl --> CompileResult
CompoundDestructorImpl --> CompileResultCollector
CompoundDestructorImpl --> CompileResults
CompoundDestructorImpl --> Function
class CompoundDestructorImpl
CompoundDestructor <|-- CompoundDestructorImpl
Not --> Option
Not --> CompileResult
Not --> Node
Not --> NodeRule
Not --> PrefixRule
Not --> StripRule
Not --> TypeRule
Not --> LazyRule
Not --> Deserializers
class Not
Value <|-- Not
Compiler --> CompileResult
Compiler --> JavaRootSegment
Compiler --> Root
Compiler --> UnitSet
interface Compiler
MapCollector --> Tuple2
MapCollector --> Collector
class MapCollector
Collector <|-- MapCollector
TypeScriptMethodHeader --> Serializable
interface TypeScriptMethodHeader
Serializable <|-- TypeScriptMethodHeader
Values --> Option
Values --> List
Values --> Lists
Values --> Iters
Values --> ListCollector
Values --> CompileResult
Values --> CompileResults
Values --> Node
Values --> NodeRule
Values --> OrRule
Values --> PrefixRule
Values --> Rule
Values --> StripRule
Values --> SuffixRule
Values --> TypeRule
Values --> CommonLang
Values --> Deserializers
Values --> LazyRule
class Values
Folder --> DivideState
interface Folder
Deserializers --> None
Deserializers --> Option
Deserializers --> Some
Deserializers --> List
Deserializers --> Lists
Deserializers --> Iters
Deserializers --> CompileResult
Deserializers --> CompileResults
Deserializers --> NodeContext
Deserializers --> CompileError
Deserializers --> InitialDestructor
Deserializers --> InitialDestructorImpl
Deserializers --> Node
Deserializers --> ImmutableCompileError
Deserializers --> TypedDeserializer
class Deserializers
ParseUnit --> NodeList
ParseUnit --> ParseState
ParseUnit --> BiFunction
interface ParseUnit
RuleGenerator --> Lists
RuleGenerator --> CompileResult
RuleGenerator --> CompileResultCollector
RuleGenerator --> NodeContext
RuleGenerator --> CompileError
RuleGenerator --> Node
RuleGenerator --> Rule
RuleGenerator --> ImmutableCompileError
RuleGenerator --> UnitSetCollector
RuleGenerator --> Unit
RuleGenerator --> UnitSet
class RuleGenerator
Generator <|-- RuleGenerator
Passer --> Node
Passer --> ParseState
Passer --> ParseResult
interface Passer
TypescriptRoot --> List
TypescriptRoot --> MapNode
TypescriptRoot --> Node
TypescriptRoot --> Serializable
class TypescriptRoot
Serializable <|-- TypescriptRoot
StructureMembers --> Lists
StructureMembers --> CompileResult
StructureMembers --> Node
StructureMembers --> OrRule
StructureMembers --> Rule
StructureMembers --> TypeRule
StructureMembers --> JavaLang
StructureMembers --> LazyRule
StructureMembers --> MutableLazyRule
StructureMembers --> Deserializers
class StructureMembers
CompileApplication --> Option
CompileApplication --> Some
CompileApplication --> Error
CompileApplication --> Compiler
CompileApplication --> ApplicationError
CompileApplication --> ThrowableError
CompileApplication --> Targets
CompileApplication --> Serializable
CompileApplication --> JavaRootSegment
CompileApplication --> Root
CompileApplication --> UnitSet
class CompileApplication
Application <|-- CompileApplication
Lambda --> Option
Lambda --> Lists
Lambda --> CompileResult
Lambda --> Node
Lambda --> LocatingRule
Lambda --> NodeListRule
Lambda --> NodeRule
Lambda --> OrRule
Lambda --> PrefixRule
Lambda --> Rule
Lambda --> StripRule
Lambda --> SuffixRule
Lambda --> TypeRule
Lambda --> CommonLang
Lambda --> LazyRule
Lambda --> ValueFolder
Lambda --> Deserializers
class Lambda
Value <|-- Lambda
Block --> Option
Block --> List
Block --> CompileResult
Block --> Node
Block --> LocatingRule
Block --> NodeRule
Block --> Rule
Block --> Splitter
Block --> StripRule
Block --> SuffixRule
Block --> TypeRule
Block --> FoldingDivider
Block --> DividingSplitter
Block --> BlockFolder
Block --> CommonLang
Block --> LazyRule
Block --> Deserializers
class Block
FunctionSegment <|-- Block
TypescriptMethod --> MapNode
TypescriptMethod --> Node
class TypescriptMethod
TypescriptStructureMember <|-- TypescriptMethod
JavaMethodHeader --> Lists
JavaMethodHeader --> CompileResult
JavaMethodHeader --> Node
JavaMethodHeader --> Deserializers
interface JavaMethodHeader
OrState --> None
OrState --> Option
OrState --> Some
OrState --> List
OrState --> Lists
OrState --> Err
OrState --> Ok
OrState --> CompileResult
OrState --> CompileResults
OrState --> Context
OrState --> CompileError
OrState --> ImmutableCompileError
class OrState
Arguments --> Lists
Arguments --> CompileResult
Arguments --> Node
Arguments --> NodeListRule
Arguments --> OrRule
Arguments --> Rule
Arguments --> Deserializers
class Arguments
ParseState --> Location
interface ParseState
MapUnitSet --> Tuple2
MapUnitSet --> Map
MapUnitSet --> MapCollector
MapUnitSet --> Maps
MapUnitSet --> Iter
MapUnitSet --> CompileResult
MapUnitSet --> CompileResultCollector
MapUnitSet --> Location
MapUnitSet --> Function
class MapUnitSet
UnitSet <|-- MapUnitSet
StructureStatement --> Option
StructureStatement --> Lists
StructureStatement --> CompileResult
StructureStatement --> MapNode
StructureStatement --> Node
StructureStatement --> NodeRule
StructureStatement --> OrRule
StructureStatement --> Rule
StructureStatement --> StripRule
StructureStatement --> SuffixRule
StructureStatement --> TypeRule
StructureStatement --> Deserializers
StructureStatement --> LazyRule
class StructureStatement
JavaStructureMember <|-- StructureStatement
TypescriptStructureMember --> Serializable
interface TypescriptStructureMember
Serializable <|-- TypescriptStructureMember
Location --> List
Location --> Joiner
class Location
JavaNamespacedNode --> Option
JavaNamespacedNode --> List
JavaNamespacedNode --> Iters
JavaNamespacedNode --> CompileResult
JavaNamespacedNode --> InitialDestructor
JavaNamespacedNode --> MapNode
JavaNamespacedNode --> Node
JavaNamespacedNode --> NodeListRule
JavaNamespacedNode --> PrefixRule
JavaNamespacedNode --> Rule
JavaNamespacedNode --> StringRule
JavaNamespacedNode --> StripRule
JavaNamespacedNode --> SuffixRule
JavaNamespacedNode --> TypeRule
JavaNamespacedNode --> DelimitedFolder
JavaNamespacedNode --> Deserializers
class JavaNamespacedNode
JavaRootSegment <|-- JavaNamespacedNode
StripRule --> CompileResult
StripRule --> Node
class StripRule
Rule <|-- StripRule
CompileErrors --> Err
CompileErrors --> CompileResult
CompileErrors --> CompileResults
CompileErrors --> NodeContext
CompileErrors --> StringContext
CompileErrors --> Node
CompileErrors --> ImmutableCompileError
class CompileErrors
Else --> Option
Else --> CompileResult
Else --> Node
Else --> Deserializers
class Else
BlockHeader <|-- Else
Parser --> UnitSet
Parser --> Stage
interface Parser
Stage <|-- Parser
Lexer --> Node
Lexer --> UnitSet
Lexer --> Stage
interface Lexer
Stage <|-- Lexer
CompoundDestructor --> Option
CompoundDestructor --> Tuple2
CompoundDestructor --> List
CompoundDestructor --> CompileResult
CompoundDestructor --> Function
interface CompoundDestructor
IOResult --> Result
IOResult --> IOException
IOResult --> Function
interface IOResult
Annotation --> CompileResult
Annotation --> Node
Annotation --> Deserializers
class Annotation
Result --> Tuple2
Result --> Function
Result --> Supplier
interface Result
InitialDestructorImpl --> Tuple2
InitialDestructorImpl --> List
InitialDestructorImpl --> ListCollector
InitialDestructorImpl --> CompileResult
InitialDestructorImpl --> CompileResultCollector
InitialDestructorImpl --> CompileResults
InitialDestructorImpl --> Deserializer
InitialDestructorImpl --> Function
InitialDestructorImpl --> Supplier
class InitialDestructorImpl
InitialDestructor <|-- InitialDestructorImpl
Main --> Console
Main --> Option
Main --> Some
Main --> Error
Main --> Iters
Main --> Result
Main --> LexingStage
Main --> PlantUMLTargetPlatform
Main --> TargetPlatform
Main --> TypeScriptTargetPlatform
Main --> ApplicationError
Main --> PathSources
Main --> Sources
Main --> JavaLang
Main --> JavaRootSegment
Main --> Root
Main --> Lexer
Main --> RuleLexer
Main --> UnitSet
Main --> Paths
class Main
class Console
TypeScriptRootSegment --> Serializable
interface TypeScriptRootSegment
Serializable <|-- TypeScriptRootSegment
UnitSetCollector --> Collector
UnitSetCollector --> MapUnitSet
UnitSetCollector --> Unit
UnitSetCollector --> UnitSet
class UnitSetCollector
Collector <|-- UnitSetCollector
enum ConditionalType
TypedDeserializer --> Option
TypedDeserializer --> CompileResult
TypedDeserializer --> Node
interface TypedDeserializer
ContextRule --> Lists
ContextRule --> CompileResult
ContextRule --> NodeContext
ContextRule --> CompileError
ContextRule --> Node
ContextRule --> StringContext
ContextRule --> ImmutableCompileError
class ContextRule
Rule <|-- ContextRule
Selector --> Option
Selector --> Tuple2
Selector --> List
interface Selector
RangeHead --> None
RangeHead --> Option
RangeHead --> Some
class RangeHead
Head <|-- RangeHead
Source --> IOResult
Source --> Location
interface Source
TemplateType --> Option
TemplateType --> List
TemplateType --> Lists
TemplateType --> CompileResult
TemplateType --> MapNode
TemplateType --> Node
TemplateType --> LocatingRule
TemplateType --> NodeListRule
TemplateType --> NodeRule
TemplateType --> OrRule
TemplateType --> Rule
TemplateType --> StripRule
TemplateType --> SuffixRule
TemplateType --> TypeRule
TemplateType --> Deserializers
class TemplateType
JavaType <|-- TemplateType
TypeScriptType <|-- TemplateType
SimpleUnit --> CompileResult
SimpleUnit --> Location
SimpleUnit --> BiFunction
SimpleUnit --> Function
class SimpleUnit
Unit <|-- SimpleUnit
Lists --> ArrayList
Lists --> Arrays
class Lists
enum PlantUMLStructureType
TypeScriptType --> Serializable
interface TypeScriptType
Serializable <|-- TypeScriptType
TypeScriptParameter --> Serializable
interface TypeScriptParameter
Serializable <|-- TypeScriptParameter
Deserializer --> Option
Deserializer --> CompileResult
Deserializer --> Node
interface Deserializer
interface Filter
ThrowableError --> Error
ThrowableError --> PrintWriter
ThrowableError --> StringWriter
class ThrowableError
Error <|-- ThrowableError
None --> Consumer
None --> Function
None --> Predicate
None --> Supplier
class None
Option <|-- None
JVMList --> None
JVMList --> Option
JVMList --> Some
JVMList --> Tuple2
JVMList --> HeadedIter
JVMList --> RangeHead
JVMList --> Iter
JVMList --> ListCollector
JVMList --> ArrayList
JVMList --> BiFunction
class JVMList
List <|-- JVMList
EnumValues --> Option
EnumValues --> List
EnumValues --> Lists
EnumValues --> CompileResult
EnumValues --> MapNode
EnumValues --> Node
EnumValues --> FilterRule
EnumValues --> LocatingRule
EnumValues --> NodeListRule
EnumValues --> OrRule
EnumValues --> Rule
EnumValues --> StringRule
EnumValues --> StripRule
EnumValues --> SuffixRule
EnumValues --> TypeRule
EnumValues --> Deserializers
EnumValues --> ValueFolder
class EnumValues
JavaStructureMember <|-- EnumValues
enum PostVariant
Generator --> Node
Generator --> UnitSet
Generator --> Stage
interface Generator
Stage <|-- Generator
Max --> Optional
class Max
Collector <|-- Max
JavaRootSegment --> Serializable
interface JavaRootSegment
Serializable <|-- JavaRootSegment
DividingSplitter --> Option
DividingSplitter --> Tuple2
DividingSplitter --> List
DividingSplitter --> ListCollector
DividingSplitter --> Splitter
DividingSplitter --> Divider
class DividingSplitter
Splitter <|-- DividingSplitter
Types --> Lists
Types --> CompileResult
Types --> Node
Types --> OrRule
Types --> Rule
Types --> LazyRule
Types --> MutableLazyRule
Types --> Deserializers
class Types
EmptyHead --> None
EmptyHead --> Option
class EmptyHead
Head <|-- EmptyHead
NodeListCollector --> Collector
class NodeListCollector
Collector <|-- NodeListCollector
Symbols --> Option
Symbols --> CompileResult
Symbols --> Node
Symbols --> FilterRule
Symbols --> Rule
Symbols --> StringRule
Symbols --> StripRule
Symbols --> TypeRule
Symbols --> Deserializers
class Symbols
Stage --> CompileResult
interface Stage
CompileResults --> Err
CompileResults --> Ok
CompileResults --> Result
CompileResults --> Context
CompileResults --> NodeContext
CompileResults --> StringContext
CompileResults --> CompileError
CompileResults --> Node
CompileResults --> ImmutableCompileError
class CompileResults
PathSources --> List
PathSources --> Iter
PathSources --> ListCollector
PathSources --> ResultCollector
PathSources --> Result
PathSources --> IOResult
PathSources --> InlineIOResult
PathSources --> SafeFiles
PathSources --> SimpleUnit
PathSources --> Unit
PathSources --> UnitSet
PathSources --> IOException
PathSources --> Files
PathSources --> Path
class PathSources
Sources <|-- PathSources
Map --> Option
Map --> Tuple2
Map --> Iter
Map --> Function
Map --> Supplier
interface Map
PlantUMLTargetPlatform --> Application
PlantUMLTargetPlatform --> CompileApplication
PlantUMLTargetPlatform --> Compiler
PlantUMLTargetPlatform --> StagedCompiler
PlantUMLTargetPlatform --> Rule
PlantUMLTargetPlatform --> PathTargets
PlantUMLTargetPlatform --> Targets
PlantUMLTargetPlatform --> JavaPlantUMLParser
PlantUMLTargetPlatform --> PlantUMLRoot
PlantUMLTargetPlatform --> Generator
PlantUMLTargetPlatform --> RuleGenerator
PlantUMLTargetPlatform --> Path
PlantUMLTargetPlatform --> Paths
class PlantUMLTargetPlatform
TargetPlatform <|-- PlantUMLTargetPlatform
MutableLazyRule --> None
MutableLazyRule --> Option
MutableLazyRule --> Some
MutableLazyRule --> CompileResult
MutableLazyRule --> CompileErrors
MutableLazyRule --> Node
MutableLazyRule --> Rule
class MutableLazyRule
LazyRule <|-- MutableLazyRule
FirstSelector --> Option
FirstSelector --> Tuple2
FirstSelector --> List
FirstSelector --> Joiner
class FirstSelector
Selector <|-- FirstSelector
Constructor --> Option
Constructor --> CompileResult
Constructor --> MapNode
Constructor --> Node
Constructor --> Deserializers
class Constructor
JavaMethodHeader <|-- Constructor
TypeScriptMethodHeader <|-- Constructor
ExactRule --> Ok
ExactRule --> CompileResult
ExactRule --> CompileResults
ExactRule --> CompileErrors
ExactRule --> MapNode
ExactRule --> Node
class ExactRule
Rule <|-- ExactRule
class StringContext
Context <|-- StringContext
JavaMethod --> Option
JavaMethod --> List
JavaMethod --> Lists
JavaMethod --> CompileResult
JavaMethod --> InitialDestructor
JavaMethod --> MapNode
JavaMethod --> Node
JavaMethod --> FilterRule
JavaMethod --> LocatingRule
JavaMethod --> NodeRule
JavaMethod --> OrRule
JavaMethod --> PrefixRule
JavaMethod --> Rule
JavaMethod --> StringRule
JavaMethod --> StripRule
JavaMethod --> SuffixRule
JavaMethod --> TypeRule
JavaMethod --> CommonLang
JavaMethod --> Deserializers
JavaMethod --> JavaLang
JavaMethod --> OptionNodeListRule
class JavaMethod
JavaStructureMember <|-- JavaMethod
InlinePassResult --> None
InlinePassResult --> Option
InlinePassResult --> Some
InlinePassResult --> Ok
InlinePassResult --> CompileResult
InlinePassResult --> CompileResults
InlinePassResult --> Node
InlinePassResult --> ParseState
InlinePassResult --> ParseUnit
InlinePassResult --> ParseUnitImpl
InlinePassResult --> Supplier
class InlinePassResult
ParseResult <|-- InlinePassResult
InitialDestructor --> List
InitialDestructor --> CompileResult
InitialDestructor --> Deserializer
InitialDestructor --> Function
InitialDestructor --> Supplier
interface InitialDestructor
TypeRule --> Lists
TypeRule --> CompileResult
TypeRule --> CompileResults
TypeRule --> Context
TypeRule --> NodeContext
TypeRule --> StringContext
TypeRule --> CompileError
TypeRule --> CompileErrors
TypeRule --> Node
TypeRule --> ImmutableCompileError
class TypeRule
Rule <|-- TypeRule
class SymbolFilter
Filter <|-- SymbolFilter
Post --> Option
Post --> CompileResult
Post --> Node
Post --> NodeRule
Post --> Rule
Post --> StripRule
Post --> SuffixRule
Post --> TypeRule
Post --> Deserializers
class Post
FunctionSegmentValue <|-- Post
JavaStructureNode --> Option
JavaStructureNode --> List
JavaStructureNode --> MapNode
JavaStructureNode --> Node
class JavaStructureNode
JavaRootSegment <|-- JavaStructureNode
OrRule --> List
OrRule --> Iter
OrRule --> CompileResult
OrRule --> Context
OrRule --> NodeContext
OrRule --> StringContext
OrRule --> Node
OrRule --> Function
class OrRule
Rule <|-- OrRule
Iter --> Option
Iter --> Collector
Iter --> Result
Iter --> BiFunction
Iter --> Function
Iter --> Predicate
interface Iter
NodeRule --> CompileResult
NodeRule --> MapNode
NodeRule --> Node
class NodeRule
Rule <|-- NodeRule
BlockFolder --> DivideState
BlockFolder --> Folder
class BlockFolder
Folder <|-- BlockFolder
Break --> Option
Break --> CompileResult
Break --> Node
Break --> Deserializers
class Break
FunctionSegmentValue <|-- Break
DelimitedFolder --> DivideState
class DelimitedFolder
Folder <|-- DelimitedFolder
Some --> Consumer
Some --> Function
Some --> Predicate
Some --> Supplier
class Some
Option <|-- Some
Deserializer --> CompileResult
Deserializer --> Node
Deserializer --> Serializable
interface Deserializer
YieldNode --> Option
YieldNode --> CompileResult
YieldNode --> Node
YieldNode --> NodeRule
YieldNode --> PrefixRule
YieldNode --> Rule
YieldNode --> StripRule
YieldNode --> TypeRule
YieldNode --> Deserializers
class YieldNode
FunctionSegmentValue <|-- YieldNode
ParameterizedMethodHeader --> List
ParameterizedMethodHeader --> Node
ParameterizedMethodHeader --> Serializable
class ParameterizedMethodHeader
Serializable <|-- ParameterizedMethodHeader
Sources --> IOResult
Sources --> UnitSet
interface Sources
Continue --> Option
Continue --> CompileResult
Continue --> Node
Continue --> Deserializers
class Continue
FunctionSegmentValue <|-- Continue
TreeParser --> Tuple2
TreeParser --> CompileResult
TreeParser --> CompileResultCollector
TreeParser --> CompileResults
TreeParser --> Node
TreeParser --> NodeList
TreeParser --> Location
TreeParser --> UnitSetCollector
TreeParser --> AfterAll
TreeParser --> ParseUnit
TreeParser --> ParseUnitImpl
TreeParser --> Passer
TreeParser --> Unit
TreeParser --> UnitSet
class TreeParser
Parser <|-- TreeParser
OptionNodeListRule --> Lists
OptionNodeListRule --> CompileResult
OptionNodeListRule --> Node
OptionNodeListRule --> OrRule
OptionNodeListRule --> Rule
class OptionNodeListRule
Rule <|-- OptionNodeListRule
JavaPlantUMLParser --> Option
JavaPlantUMLParser --> List
JavaPlantUMLParser --> Lists
JavaPlantUMLParser --> Iter
JavaPlantUMLParser --> Iters
JavaPlantUMLParser --> Joiner
JavaPlantUMLParser --> ListCollector
JavaPlantUMLParser --> CompileResult
JavaPlantUMLParser --> CompileResults
JavaPlantUMLParser --> Location
JavaPlantUMLParser --> ArrayType
JavaPlantUMLParser --> Base
JavaPlantUMLParser --> Root
JavaPlantUMLParser --> JavaRootSegment
JavaPlantUMLParser --> JavaNamespacedNode
JavaPlantUMLParser --> PlantUMLDependency
JavaPlantUMLParser --> PlantUMLFooter
JavaPlantUMLParser --> PlantUMLHeader
JavaPlantUMLParser --> PlantUMLInherits
JavaPlantUMLParser --> PlantUMLRoot
JavaPlantUMLParser --> PlantUMLRootSegment
JavaPlantUMLParser --> PlantUMLStructure
JavaPlantUMLParser --> PlantUMLStructureType
JavaPlantUMLParser --> QualifiedType
JavaPlantUMLParser --> Segment
JavaPlantUMLParser --> JavaStructureNode
JavaPlantUMLParser --> JavaStructureType
JavaPlantUMLParser --> Symbol
JavaPlantUMLParser --> TemplateType
JavaPlantUMLParser --> JavaType
JavaPlantUMLParser --> VariadicType
JavaPlantUMLParser --> Whitespace
JavaPlantUMLParser --> Parser
JavaPlantUMLParser --> MapUnitSet
JavaPlantUMLParser --> SimpleUnit
JavaPlantUMLParser --> Unit
JavaPlantUMLParser --> UnitSet
class JavaPlantUMLParser
Parser <|-- JavaPlantUMLParser
enum Operator
ValueFolder --> DivideState
ValueFolder --> Folder
class ValueFolder
Folder <|-- ValueFolder
InvokableNode --> Option
InvokableNode --> List
InvokableNode --> Lists
InvokableNode --> CompileResult
InvokableNode --> Node
InvokableNode --> LocatingRule
InvokableNode --> NodeRule
InvokableNode --> OrRule
InvokableNode --> Rule
InvokableNode --> Splitter
InvokableNode --> StripRule
InvokableNode --> SuffixRule
InvokableNode --> TypeRule
InvokableNode --> FoldingDivider
InvokableNode --> DividingSplitter
InvokableNode --> InvocationFolder
InvokableNode --> Deserializers
class InvokableNode
Value <|-- InvokableNode
FunctionSegmentValue <|-- InvokableNode
StringNode --> Option
StringNode --> CompileResult
StringNode --> Node
StringNode --> PrefixRule
StringNode --> Rule
StringNode --> StringRule
StringNode --> StripRule
StringNode --> SuffixRule
StringNode --> TypeRule
StringNode --> Deserializers
class StringNode
Value <|-- StringNode
JavaStructureMember --> Serializable
interface JavaStructureMember
Serializable <|-- JavaStructureMember
SafeFiles --> None
SafeFiles --> Option
SafeFiles --> Some
SafeFiles --> JVMList
SafeFiles --> Iter
SafeFiles --> Err
SafeFiles --> Ok
SafeFiles --> IOException
SafeFiles --> Files
SafeFiles --> Path
SafeFiles --> Collectors
SafeFiles --> Stream
class SafeFiles
interface JavaParameter
interface Assignable
TypeParam --> CompileResult
TypeParam --> MapNode
TypeParam --> Node
TypeParam --> Deserializers
TypeParam --> Serializable
class TypeParam
Serializable <|-- TypeParam
FilterRule --> CompileResult
FilterRule --> CompileErrors
FilterRule --> Node
FilterRule --> Filter
FilterRule --> NumberFilter
FilterRule --> SymbolFilter
class FilterRule
Rule <|-- FilterRule
TypescriptLang --> Lists
TypescriptLang --> LocatingRule
TypescriptLang --> NodeRule
TypescriptLang --> OrRule
TypescriptLang --> PrefixRule
TypescriptLang --> Rule
TypescriptLang --> StringRule
TypescriptLang --> StripRule
TypescriptLang --> SuffixRule
TypescriptLang --> TypeRule
TypescriptLang --> FunctionSegment
TypescriptLang --> Modifier
TypescriptLang --> Parameters
TypescriptLang --> StructureStatement
TypescriptLang --> Symbols
TypescriptLang --> TemplateType
TypescriptLang --> TypeScriptImport
TypescriptLang --> TypescriptStructureNode
TypescriptLang --> Values
TypescriptLang --> Whitespace
class TypescriptLang
TypeScriptTargetPlatform --> Application
TypeScriptTargetPlatform --> CompileApplication
TypeScriptTargetPlatform --> Compiler
TypeScriptTargetPlatform --> StagedCompiler
TypeScriptTargetPlatform --> Rule
TypeScriptTargetPlatform --> PathTargets
TypeScriptTargetPlatform --> Targets
TypeScriptTargetPlatform --> TypescriptLang
TypeScriptTargetPlatform --> JavaRootSegment
TypeScriptTargetPlatform --> Root
TypeScriptTargetPlatform --> TypescriptRoot
TypeScriptTargetPlatform --> Generator
TypeScriptTargetPlatform --> RuleGenerator
TypeScriptTargetPlatform --> Parser
TypeScriptTargetPlatform --> Path
TypeScriptTargetPlatform --> Paths
class TypeScriptTargetPlatform
TargetPlatform <|-- TypeScriptTargetPlatform
Targets --> IOException
Targets --> Option
Targets --> UnitSet
interface Targets
Caller --> Lists
Caller --> CompileResult
Caller --> Node
Caller --> Deserializers
interface Caller
Unit --> CompileResult
Unit --> Location
Unit --> BiFunction
Unit --> Function
interface Unit
FlattenJava --> Some
FlattenJava --> ListCollector
FlattenJava --> CompileResults
FlattenJava --> InlineNodeList
FlattenJava --> Node
FlattenJava --> NodeList
FlattenJava --> InlinePassResult
FlattenJava --> ParseResult
FlattenJava --> ParseUnit
FlattenJava --> ParseUnitImpl
FlattenJava --> Passer
FlattenJava --> ParseState
class FlattenJava
Passer <|-- FlattenJava
interface Argument
Parameters --> Lists
Parameters --> CompileResult
Parameters --> Node
Parameters --> NodeListRule
Parameters --> OrRule
Parameters --> Rule
Parameters --> ValueFolder
Parameters --> Deserializers
class Parameters
Maps --> HashMap
class Maps
class Tuple2
StagedCompiler --> CompileResult
StagedCompiler --> Serializable
StagedCompiler --> JavaRootSegment
StagedCompiler --> Root
StagedCompiler --> Generator
StagedCompiler --> Parser
StagedCompiler --> UnitSet
class StagedCompiler
Compiler <|-- StagedCompiler
LazyRule --> Rule
interface LazyRule
Rule <|-- LazyRule
JavaTypescriptParser --> List
JavaTypescriptParser --> Lists
JavaTypescriptParser --> ListCollector
JavaTypescriptParser --> CompileResult
JavaTypescriptParser --> CompileResultCollector
JavaTypescriptParser --> CompileResults
JavaTypescriptParser --> Location
JavaTypescriptParser --> UnitSetCollector
JavaTypescriptParser --> ArrayType
JavaTypescriptParser --> Constructor
JavaTypescriptParser --> Definition
JavaTypescriptParser --> EnumValues
JavaTypescriptParser --> JavaDefinition
JavaTypescriptParser --> JavaMethod
JavaTypescriptParser --> JavaMethodHeader
JavaTypescriptParser --> JavaNamespacedNode
JavaTypescriptParser --> JavaParameter
JavaTypescriptParser --> JavaRootSegment
JavaTypescriptParser --> JavaStructureMember
JavaTypescriptParser --> JavaStructureNode
JavaTypescriptParser --> JavaType
JavaTypescriptParser --> ParameterizedMethodHeader
JavaTypescriptParser --> Root
JavaTypescriptParser --> Segment
JavaTypescriptParser --> StructureStatement
JavaTypescriptParser --> StructureValue
JavaTypescriptParser --> TypeScriptDefinition
JavaTypescriptParser --> TypeScriptImport
JavaTypescriptParser --> TypeScriptMethodHeader
JavaTypescriptParser --> TypeScriptParameter
JavaTypescriptParser --> TypeScriptRootSegment
JavaTypescriptParser --> TypeScriptType
JavaTypescriptParser --> TypescriptMethod
JavaTypescriptParser --> TypescriptRoot
JavaTypescriptParser --> TypescriptStructureMember
JavaTypescriptParser --> TypescriptStructureNode
JavaTypescriptParser --> TypescriptStructureType
JavaTypescriptParser --> VariadicType
JavaTypescriptParser --> Whitespace
JavaTypescriptParser --> Parser
JavaTypescriptParser --> SimpleUnit
JavaTypescriptParser --> Unit
JavaTypescriptParser --> UnitSet
class JavaTypescriptParser
Parser <|-- JavaTypescriptParser
ImmutableCompileError --> List
ImmutableCompileError --> Lists
ImmutableCompileError --> Iter
ImmutableCompileError --> Joiner
ImmutableCompileError --> Max
ImmutableCompileError --> Context
ImmutableCompileError --> CompileError
class ImmutableCompileError
CompileError <|-- ImmutableCompileError
NodeList --> Option
NodeList --> Iter
NodeList --> CompileResult
NodeList --> Function
interface NodeList
LastSelector --> Option
LastSelector --> Tuple2
LastSelector --> List
LastSelector --> Joiner
class LastSelector
Selector <|-- LastSelector
RootDeserializer --> CompileResult
RootDeserializer --> Node
RootDeserializer --> Deserializers
RootDeserializer --> Serializable
class RootDeserializer
Deserializer <|-- RootDeserializer
InlineCompileResult --> Tuple2
InlineCompileResult --> Result
InlineCompileResult --> CompileError
InlineCompileResult --> BiFunction
InlineCompileResult --> Function
InlineCompileResult --> Supplier
class InlineCompileResult
CompileResult <|-- InlineCompileResult
RuleLexer --> CompileResult
RuleLexer --> CompileResultCollector
RuleLexer --> Node
RuleLexer --> Rule
RuleLexer --> UnitSetCollector
RuleLexer --> Unit
RuleLexer --> UnitSet
class RuleLexer
Lexer <|-- RuleLexer
Modifier --> CompileResult
Modifier --> MapNode
Modifier --> Node
Modifier --> NodeListRule
Modifier --> Rule
Modifier --> StringRule
Modifier --> StripRule
Modifier --> DelimitedFolder
Modifier --> Deserializers
Modifier --> Serializable
class Modifier
Serializable <|-- Modifier
Try --> Option
Try --> CompileResult
Try --> Node
Try --> Deserializers
class Try
BlockHeader <|-- Try
FunctionStatement --> Option
FunctionStatement --> CompileResult
FunctionStatement --> Node
FunctionStatement --> NodeRule
FunctionStatement --> Rule
FunctionStatement --> StripRule
FunctionStatement --> SuffixRule
FunctionStatement --> TypeRule
FunctionStatement --> Deserializers
class FunctionStatement
FunctionSegment <|-- FunctionStatement
OperationDeserializer --> Option
OperationDeserializer --> CompileResult
OperationDeserializer --> Node
OperationDeserializer --> Deserializers
class OperationDeserializer
TypedDeserializer <|-- OperationDeserializer
TypeScriptImport --> List
TypeScriptImport --> MapNode
TypeScriptImport --> Node
TypeScriptImport --> LocatingRule
TypeScriptImport --> NodeListRule
TypeScriptImport --> PrefixRule
TypeScriptImport --> Rule
TypeScriptImport --> StringRule
TypeScriptImport --> SuffixRule
TypeScriptImport --> TypeRule
TypeScriptImport --> DelimitedDivider
TypeScriptImport --> DelimitedFolder
class TypeScriptImport
TypeScriptRootSegment <|-- TypeScriptImport
PlantUMLHeader --> MapNode
PlantUMLHeader --> Node
PlantUMLHeader --> ExactRule
PlantUMLHeader --> TypeRule
class PlantUMLHeader
PlantUMLRootSegment <|-- PlantUMLHeader
enum TypescriptStructureType
Rule --> CompileResult
Rule --> Node
interface Rule
CompileResultCollector --> Collector
CompileResultCollector --> Ok
class CompileResultCollector
Collector <|-- CompileResultCollector
interface Error
PathTargets --> Option
PathTargets --> Iters
PathTargets --> Location
PathTargets --> SafeFiles
PathTargets --> Unit
PathTargets --> UnitSet
PathTargets --> IOException
PathTargets --> Files
PathTargets --> Path
class PathTargets
Targets <|-- PathTargets
PlantUMLFooter --> MapNode
PlantUMLFooter --> Node
PlantUMLFooter --> ExactRule
PlantUMLFooter --> TypeRule
class PlantUMLFooter
PlantUMLRootSegment <|-- PlantUMLFooter
SingleHead --> None
SingleHead --> Option
SingleHead --> Some
class SingleHead
Head <|-- SingleHead
NumberNode --> Option
NumberNode --> CompileResult
NumberNode --> Node
NumberNode --> FilterRule
NumberNode --> Rule
NumberNode --> StringRule
NumberNode --> StripRule
NumberNode --> TypeRule
NumberNode --> Deserializers
class NumberNode
Value <|-- NumberNode
Option --> Consumer
Option --> Function
Option --> Predicate
Option --> Supplier
interface Option
PlantUMLRoot --> List
PlantUMLRoot --> MapNode
PlantUMLRoot --> Node
PlantUMLRoot --> NodeListRule
PlantUMLRoot --> Rule
PlantUMLRoot --> StatementFolder
PlantUMLRoot --> Serializable
class PlantUMLRoot
Serializable <|-- PlantUMLRoot
Ok --> Tuple2
Ok --> Function
Ok --> Supplier
class Ok
Result <|-- Ok
LocatingRule --> Tuple2
LocatingRule --> CompileResult
LocatingRule --> CompileErrors
LocatingRule --> Node
LocatingRule --> FirstLocator
LocatingRule --> LastLocator
LocatingRule --> Locator
class LocatingRule
Rule <|-- LocatingRule
SuffixRule --> CompileResult
SuffixRule --> CompileErrors
SuffixRule --> Node
class SuffixRule
Rule <|-- SuffixRule
EmptyAfterAll --> Node
EmptyAfterAll --> UnitSet
class EmptyAfterAll
AfterAll <|-- EmptyAfterAll
Structures --> Lists
Structures --> ContextRule
Structures --> FilterRule
Structures --> LocatingRule
Structures --> NodeListRule
Structures --> OrRule
Structures --> Rule
Structures --> StringRule
Structures --> StripRule
Structures --> SuffixRule
Structures --> TypeRule
Structures --> CommonLang
Structures --> JavaLang
Structures --> ValueFolder
class Structures
LastLocator --> None
LastLocator --> Option
LastLocator --> Some
class LastLocator
Locator <|-- LastLocator
MutableDivideState --> None
MutableDivideState --> Option
MutableDivideState --> Some
MutableDivideState --> Tuple2
MutableDivideState --> List
MutableDivideState --> Lists
MutableDivideState --> Iter
class MutableDivideState
DivideState <|-- MutableDivideState
CompileError --> Error
interface CompileError
Error <|-- CompileError
Locator --> Option
interface Locator
PlantUMLRootSegment --> Serializable
interface PlantUMLRootSegment
Serializable <|-- PlantUMLRootSegment
QualifiedType --> Option
QualifiedType --> List
QualifiedType --> CompileResult
QualifiedType --> MapNode
QualifiedType --> Node
QualifiedType --> NodeListRule
QualifiedType --> Rule
QualifiedType --> TypeRule
QualifiedType --> DelimitedFolder
QualifiedType --> Deserializers
class QualifiedType
Base <|-- QualifiedType
TypeSeparatorFolder --> DivideState
TypeSeparatorFolder --> Folder
class TypeSeparatorFolder
Folder <|-- TypeSeparatorFolder
UnitSet --> Iter
UnitSet --> CompileResult
UnitSet --> Function
interface UnitSet
ParseUnitImpl --> InlineNodeList
ParseUnitImpl --> NodeList
ParseUnitImpl --> ParseState
ParseUnitImpl --> BiFunction
class ParseUnitImpl
ParseUnit <|-- ParseUnitImpl
PlantUMLDependency --> MapNode
PlantUMLDependency --> Node
PlantUMLDependency --> LocatingRule
PlantUMLDependency --> StringRule
PlantUMLDependency --> TypeRule
class PlantUMLDependency
PlantUMLRootSegment <|-- PlantUMLDependency
SwitchNode --> Option
SwitchNode --> CompileResult
SwitchNode --> Node
SwitchNode --> Deserializers
class SwitchNode
Value <|-- SwitchNode
FlatMapHead --> None
FlatMapHead --> Iter
FlatMapHead --> Option
FlatMapHead --> Function
class FlatMapHead
Head <|-- FlatMapHead
FoldingDivider --> None
FoldingDivider --> Option
FoldingDivider --> Some
FoldingDivider --> Tuple2
FoldingDivider --> Iter
FoldingDivider --> Folder
class FoldingDivider
Divider <|-- FoldingDivider
Whitespace --> Option
Whitespace --> CompileResult
Whitespace --> MapNode
Whitespace --> Node
Whitespace --> ExactRule
Whitespace --> Rule
Whitespace --> StripRule
Whitespace --> TypeRule
Whitespace --> Deserializers
class Whitespace
Argument <|-- Whitespace
FunctionSegment <|-- Whitespace
JavaRootSegment <|-- Whitespace
JavaParameter <|-- Whitespace
JavaStructureMember <|-- Whitespace
TypeScriptRootSegment <|-- Whitespace
TypescriptStructureMember <|-- Whitespace
TypeScriptParameter <|-- Whitespace
CommonLang --> LocatingRule
CommonLang --> NodeListRule
CommonLang --> NodeRule
CommonLang --> Rule
CommonLang --> StripRule
CommonLang --> SuffixRule
CommonLang --> TypeRule
CommonLang --> StatementFolder
class CommonLang
interface Value
Caller <|-- Value
Argument <|-- Value
Assignable <|-- Value
InvocationFolder --> DivideState
InvocationFolder --> Folder
class InvocationFolder
Folder <|-- InvocationFolder
JavaLang --> Lists
JavaLang --> FilterRule
JavaLang --> LocatingRule
JavaLang --> NodeListRule
JavaLang --> NodeRule
JavaLang --> OrRule
JavaLang --> PrefixRule
JavaLang --> Rule
JavaLang --> Splitter
JavaLang --> StringRule
JavaLang --> StripRule
JavaLang --> SuffixRule
JavaLang --> TypeRule
JavaLang --> Divider
JavaLang --> FoldingDivider
JavaLang --> DelimitedFolder
JavaLang --> DividingSplitter
JavaLang --> JavaRootSegment
JavaLang --> JavaRootSegments
JavaLang --> Modifier
JavaLang --> RootDeserializer
JavaLang --> Types
class JavaLang
StringRule --> Ok
StringRule --> CompileResult
StringRule --> CompileResults
StringRule --> CompileErrors
StringRule --> MapNode
StringRule --> Node
class StringRule
Rule <|-- StringRule
ResultCollector --> Tuple2
ResultCollector --> Ok
ResultCollector --> Result
class ResultCollector
Collector <|-- ResultCollector
FunctionSegmentValues --> Lists
FunctionSegmentValues --> CompileResult
FunctionSegmentValues --> Node
FunctionSegmentValues --> ExactRule
FunctionSegmentValues --> OrRule
FunctionSegmentValues --> Rule
FunctionSegmentValues --> TypeRule
FunctionSegmentValues --> Deserializers
class FunctionSegmentValues
VariadicType --> Option
VariadicType --> CompileResult
VariadicType --> MapNode
VariadicType --> Node
VariadicType --> NodeRule
VariadicType --> Rule
VariadicType --> StripRule
VariadicType --> SuffixRule
VariadicType --> TypeRule
VariadicType --> Deserializers
class VariadicType
JavaType <|-- VariadicType
Head --> Option
interface Head
DelimitedDivider --> Iter
DelimitedDivider --> Iters
DelimitedDivider --> Pattern
class DelimitedDivider
Divider <|-- DelimitedDivider
ParseResult --> CompileResult
ParseResult --> Node
ParseResult --> ParseUnit
ParseResult --> Supplier
interface ParseResult
StatementFolder --> DivideState
class StatementFolder
Folder <|-- StatementFolder
EnumValue --> CompileResult
EnumValue --> Node
EnumValue --> Deserializers
class EnumValue
Symbol --> MapNode
Symbol --> Node
class Symbol
JavaType <|-- Symbol
Value <|-- Symbol
Base <|-- Symbol
TypeScriptType <|-- Symbol
NodeContext --> Node
class NodeContext
Context <|-- NodeContext
CompileResult --> Tuple2
CompileResult --> Result
CompileResult --> CompileError
CompileResult --> BiFunction
CompileResult --> Function
CompileResult --> Supplier
interface CompileResult
class NumberFilter
Filter <|-- NumberFilter
DivideState --> Tuple2
DivideState --> Option
DivideState --> Iter
interface DivideState
enum JavaStructureType
JVMMap --> None
JVMMap --> Option
JVMMap --> Some
JVMMap --> Tuple2
JVMMap --> JVMList
JVMMap --> Iter
JVMMap --> ArrayList
JVMMap --> HashMap
JVMMap --> Function
JVMMap --> Supplier
class JVMMap
Map <|-- JVMMap
PrefixRule --> CompileResult
PrefixRule --> CompileErrors
PrefixRule --> Node
class PrefixRule
Rule <|-- PrefixRule
LexingStage --> Result
LexingStage --> CompileResult
LexingStage --> Node
LexingStage --> ApplicationError
LexingStage --> ThrowableError
LexingStage --> Sources
LexingStage --> Lexer
LexingStage --> UnitSet
LexingStage --> Function
class LexingStage
enum AccessType
ArrayType --> Option
ArrayType --> CompileResult
ArrayType --> MapNode
ArrayType --> Node
ArrayType --> NodeRule
ArrayType --> Rule
ArrayType --> StripRule
ArrayType --> SuffixRule
ArrayType --> TypeRule
ArrayType --> Deserializers
class ArrayType
JavaType <|-- ArrayType
TypeScriptType <|-- ArrayType
PathSource --> List
PathSource --> Lists
PathSource --> IOResult
PathSource --> Location
PathSource --> SafeFiles
PathSource --> Path
class PathSource
Source <|-- PathSource
InlineNodeList --> Option
InlineNodeList --> Some
InlineNodeList --> List
InlineNodeList --> Lists
InlineNodeList --> Iter
InlineNodeList --> Joiner
InlineNodeList --> CompileResult
InlineNodeList --> CompileResultCollector
InlineNodeList --> Function
class InlineNodeList
NodeList <|-- InlineNodeList
Serializable --> Node
interface Serializable
FirstLocator --> None
FirstLocator --> Option
FirstLocator --> Some
class FirstLocator
Locator <|-- FirstLocator
Construction --> Option
Construction --> CompileResult
Construction --> Node
Construction --> NodeRule
Construction --> PrefixRule
Construction --> Rule
Construction --> StripRule
Construction --> TypeRule
Construction --> Deserializers
class Construction
Caller <|-- Construction
Node --> Option
Node --> Tuple2
Node --> List
Node --> Iter
Node --> CompileResult
Node --> Serializable
Node --> Function
interface Node
NodeListRule --> CompileResult
NodeListRule --> CompileResultCollector
NodeListRule --> MapNode
NodeListRule --> Node
NodeListRule --> NodeList
NodeListRule --> NodeListCollector
NodeListRule --> Divider
NodeListRule --> FoldingDivider
NodeListRule --> Folder
NodeListRule --> ValueFolder
class NodeListRule
Rule <|-- NodeListRule
Definition --> Option
Definition --> List
Definition --> CompileResult
Definition --> InitialDestructor
Definition --> MapNode
Definition --> Node
Definition --> Deserializers
Definition --> Serializable
class Definition
Serializable <|-- Definition
Iters --> Option
Iters --> EmptyHead
Iters --> HeadedIter
Iters --> RangeHead
Iters --> SingleHead
class Iters
TypeScriptDefinition --> Node
class TypeScriptDefinition
TypeScriptParameter <|-- TypeScriptDefinition
Assignable <|-- TypeScriptDefinition
TypeScriptMethodHeader <|-- TypeScriptDefinition
Assignables --> Lists
Assignables --> CompileResult
Assignables --> Node
Assignables --> Deserializers
class Assignables
enum NamespacedType
TypeScriptAfterPasser --> None
TypeScriptAfterPasser --> Option
TypeScriptAfterPasser --> Some
TypeScriptAfterPasser --> Lists
TypeScriptAfterPasser --> CompileResult
TypeScriptAfterPasser --> CompileResults
TypeScriptAfterPasser --> InlineNodeList
TypeScriptAfterPasser --> MapNode
TypeScriptAfterPasser --> Node
TypeScriptAfterPasser --> NodeList
TypeScriptAfterPasser --> NodeListCollector
TypeScriptAfterPasser --> Passer
TypeScriptAfterPasser --> ParseState
TypeScriptAfterPasser --> InlinePassResult
TypeScriptAfterPasser --> ParseResult
TypeScriptAfterPasser --> ParseUnit
TypeScriptAfterPasser --> ParseUnitImpl
class TypeScriptAfterPasser
Passer <|-- TypeScriptAfterPasser
interface Collector
LocatingSplitter --> Option
LocatingSplitter --> Tuple2
LocatingSplitter --> Locator
class LocatingSplitter
Splitter <|-- LocatingSplitter
CharNode --> Option
CharNode --> CompileResult
CharNode --> Node
CharNode --> PrefixRule
CharNode --> Rule
CharNode --> StringRule
CharNode --> StripRule
CharNode --> SuffixRule
CharNode --> TypeRule
CharNode --> Deserializers
class CharNode
Value <|-- CharNode
interface Context
MergeDiagram --> Tuple2
MergeDiagram --> List
MergeDiagram --> Lists
MergeDiagram --> Map
MergeDiagram --> Maps
MergeDiagram --> Iters
MergeDiagram --> ListCollector
MergeDiagram --> InlineNodeList
MergeDiagram --> MapNode
MergeDiagram --> Node
MergeDiagram --> NodeList
MergeDiagram --> Location
MergeDiagram --> AfterAll
MergeDiagram --> MapUnitSet
MergeDiagram --> SimpleUnit
MergeDiagram --> UnitSet
class MergeDiagram
AfterAll <|-- MergeDiagram
Segment --> CompileResult
Segment --> MapNode
Segment --> Node
Segment --> Deserializers
class Segment
Application --> Option
Application --> Error
Application --> JavaRootSegment
Application --> Root
Application --> UnitSet
interface Application
ImmutableParseState --> Location
class ImmutableParseState
ParseState <|-- ImmutableParseState
Conditional --> Option
Conditional --> CompileResult
Conditional --> Node
Conditional --> NodeRule
Conditional --> PrefixRule
Conditional --> Rule
Conditional --> StripRule
Conditional --> SuffixRule
Conditional --> TypeRule
Conditional --> Deserializers
class Conditional
BlockHeader <|-- Conditional
Operation --> LocatingRule
Operation --> NodeRule
Operation --> Rule
Operation --> TypeRule
class Operation
Value <|-- Operation
Divider --> Iter
interface Divider
Err --> Tuple2
Err --> Function
Err --> Supplier
class Err
Result <|-- Err
ReturnNode --> Option
ReturnNode --> CompileResult
ReturnNode --> Node
ReturnNode --> NodeRule
ReturnNode --> PrefixRule
ReturnNode --> Rule
ReturnNode --> StripRule
ReturnNode --> TypeRule
ReturnNode --> Deserializers
class ReturnNode
FunctionSegmentValue <|-- ReturnNode
FunctionSegment <|-- ReturnNode
JavaType --> Serializable
interface JavaType
Serializable <|-- JavaType
TypescriptStructureNode --> Node
TypescriptStructureNode --> LocatingRule
TypescriptStructureNode --> PrefixRule
TypescriptStructureNode --> Rule
TypescriptStructureNode --> StringRule
TypescriptStructureNode --> SuffixRule
TypescriptStructureNode --> TypeRule
TypescriptStructureNode --> CommonLang
TypescriptStructureNode --> JavaLang
TypescriptStructureNode --> TypescriptLang
class TypescriptStructureNode
TypeScriptRootSegment <|-- TypescriptStructureNode
PlantUMLAfterPasser --> Some
PlantUMLAfterPasser --> List
PlantUMLAfterPasser --> ListCollector
PlantUMLAfterPasser --> CompileResult
PlantUMLAfterPasser --> CompileResultCollector
PlantUMLAfterPasser --> CompileResults
PlantUMLAfterPasser --> CompileErrors
PlantUMLAfterPasser --> InlineNodeList
PlantUMLAfterPasser --> MapNode
PlantUMLAfterPasser --> Node
PlantUMLAfterPasser --> NodeList
PlantUMLAfterPasser --> NodeListCollector
PlantUMLAfterPasser --> StringRule
PlantUMLAfterPasser --> InlinePassResult
PlantUMLAfterPasser --> ParseResult
PlantUMLAfterPasser --> ParseUnit
PlantUMLAfterPasser --> ParseUnitImpl
PlantUMLAfterPasser --> Passer
PlantUMLAfterPasser --> ParseState
class PlantUMLAfterPasser
Passer <|-- PlantUMLAfterPasser
JavaRootSegments --> Lists
JavaRootSegments --> CompileResult
JavaRootSegments --> MapNode
JavaRootSegments --> Node
JavaRootSegments --> OrRule
JavaRootSegments --> Rule
JavaRootSegments --> Deserializers
class JavaRootSegments
HeadedIter --> Option
HeadedIter --> Iter
HeadedIter --> Collector
HeadedIter --> Ok
HeadedIter --> Result
HeadedIter --> BiFunction
HeadedIter --> Function
HeadedIter --> Predicate
class HeadedIter
Iter <|-- HeadedIter
Splitter --> Option
Splitter --> Tuple2
interface Splitter
JavaDefinition --> Option
JavaDefinition --> CompileResult
JavaDefinition --> Node
class JavaDefinition
JavaParameter <|-- JavaDefinition
Assignable <|-- JavaDefinition
JavaMethodHeader <|-- JavaDefinition
MapNode --> None
MapNode --> Option
MapNode --> Some
MapNode --> Tuple2
MapNode --> List
MapNode --> Map
MapNode --> Maps
MapNode --> Iter
MapNode --> Iters
MapNode --> Joiner
MapNode --> Ok
MapNode --> CompileResult
MapNode --> CompileResults
MapNode --> CompileErrors
MapNode --> BiFunction
MapNode --> Function
class MapNode
Node <|-- MapNode
InlineIOResult --> Result
InlineIOResult --> IOException
InlineIOResult --> Function
class InlineIOResult
IOResult <|-- InlineIOResult
@enduml
