name: Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: packages/compiler-ts/package-lock.json

      - name: Install dependencies
        working-directory: packages/compiler-ts
        run: npm install

      # The TypeScript version of the compiler isn't ready yet so we skip
      # compiling .ts files in CI to avoid noisy failures.
      # Once the TypeScript pipeline is stable this step can run `npx tsc`.
      - name: Skip TypeScript build
        run: echo "Skipping TypeScript build"

      - name: Build Java
        run: |
          mkdir -p out
          javac --release 21 --enable-preview -d out $(find packages/compiler-java/src/main/java -name '*.java')

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-out
          path: out

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: packages/compiler-ts/package-lock.json

      - name: Install dependencies
        working-directory: packages/compiler-ts
        run: npm install

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-out
          path: out

      - name: Run Java tests
        run: |
          curl -L -o junit-platform-console-standalone.jar https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.10.1/junit-platform-console-standalone-1.10.1.jar
          javac --release 21 --enable-preview -cp junit-platform-console-standalone.jar:out -d out $(find packages/compiler-java/src/test/java -name '*.java')
          java --enable-preview -jar junit-platform-console-standalone.jar --class-path out --scan-class-path
